node {
       stage ('Clone') {
           step {
              echo 'Put clone command here'
           }
       }

       stage ('Build') {
           step {
              echo 'Put Build command here'
           }
       }
}
