node {
     stage ('Clone') {
          git branch: 'main', credentialsId: 'git-prabhut', url: 'https://github.com/git-prabhut/bazel-examples'
     }

     stage ('Build') {
           echo 'Put Build command here'
     }
}
